### ISSUE TITLE
使用非阻塞方式创建多个 GeccoEngine 报错

### ISSUE THREAD

**Issue by justpsvm** [xtuhcy/gecco#38]
```java
GeccoEngine.create()
                .classpath("xxx")
                .pipelineFactory(springPipelineFactory)
                .interval(1000)
                .start(request).start();
```

如上 创建多个会出现以下异常

```
Exception in thread "GeccoEngine" java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669)
	at java.util.zip.ZipFile.access$200(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.hasNext(ZipFile.java:493)
	at java.util.zip.ZipFile$ZipEntryIterator.hasMoreElements(ZipFile.java:488)
	at java.util.jar.JarFile$JarEntryIterator.hasNext(JarFile.java:253)
	at java.util.jar.JarFile$JarEntryIterator.hasMoreElements(JarFile.java:262)
	at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:30)
	at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:26)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at org.reflections.Reflections.scan(Reflections.java:243)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at com.geccocrawler.gecco.monitor.GeccoJmx.export(GeccoJmx.java:16)
	at com.geccocrawler.gecco.GeccoEngine.run(GeccoEngine.java:250)
```

在启动时 我不想配置 `starts.json` 文件 有什么方式能够避免报错？ 如果不配置 `starts.json` 会抛一个异常。

感谢！

**Comment by xtuhcy** [comment]
目前一个GeccoEngine实例是用classpath唯一标识的,需要指定不同的classpath

**Comment by justpsvm** [comment]
在不改变 classpath 的同时，如何运行多个 还是说整个服务器端只能有一个实例？

**Comment by xtuhcy** [comment]
一般建议一类爬虫一个引擎,可以通过增加线程数量提高效率.不同类的爬虫才建议用classpath区分

**Comment by justpsvm** [comment]
在爬虫运行的同时 我还想用爬虫去爬取其它信息 它们在同一个 classpath 下，这样可以做到么？   不过我使用 run() 方式启动 不会出问题

**Comment by xtuhcy** [comment]
爬虫是有队列的,将需要继续爬取的request放入队列即可

**Comment by justpsvm** [comment]
明白你说的意思

**Comment by justpsvm** [comment]
明白你说的意思

```java
HttpRequest httpRequest = new HttpGetRequest();
httpRequest.setUrl(url);
SchedulerContext.into(httpRequest);
```

如果使用这个方式 我要知道当前爬虫的运行状态

```java
if(isRun){
SchedulerContext.into()
}else{
//create
}
```

但是我看了api文档 貌似没有提供爬虫当前的状态？

**Comment by xtuhcy** [comment]
用start()方式就行，启动一个GeccoEngine，把需要爬取的request都放到这一个GeccoEngine上。初始的request也可以放多个。可以看看这篇文章http://www.geccocrawler.com/sysc-9/

**Comment by justpsvm** [comment]
用阻塞的方式启动 不会出现这个问题 我暂时先这样处理 谢谢了！
